### ISSUE TITLE
EPG já não funciona...

### ISSUE THREAD

**Issue by base08** [f0nZ/epg-tv-portuguesa#1]
Deixou de funcionar este EPG...

**Comment by f0nZ** [comment]
Viva!

Encontra-se corrigido novamente!

Diariamente pelas 23h irá continuar normalmente as atualizações.

Cumps

base08 <notifications@github.com> escreveu no dia segunda, 29/07/2019 à(s)
22:36:

**Comment by base08** [comment]
Obrigado! Parabéns pelo serviço público, aqui em casa na Bélgica isto aprimorou a “nossa janela para Portugal”!
