### ISSUE TITLE
Sugestão de adição de canais ao EPG

### ISSUE THREAD

**Issue by pgomespxo1** [f0nZ/epg-tv-portuguesa#13]
Boa noite, em primeiro lugar queria agradecer o seu trabalho na criação desta lista EPG. Em segundo lugar queria sugerir se fosse possível adicionar mais uns canais a esta lista nomeadamente Discovery Channel fHD, História fHD, Odisseia fHD, 24 Kitchen HD e BTV (Benfica TV). Agradeço

**Comment by PTED209** [comment]
Boa tarde, Obrigado pela partilha desta excelente lista EPG. Eu também já tive uma lista destas, mas agora o programa é pago, a versão free só funciona com 20 canais. :-(
Podes adicionar mais alguns canais por favor?
Vou colocar como tinha na minha, para ser mais fácil para ti. (Estão todos a funcionar)

<channel update="i" site="tudonumclick.com" site_id="cacavision" xmltv_id="cacavision.pt">CACAVISION</channel>
<channel update="i" site="nos.pt" site_id="572" xmltv_id="casaecozinha.pt">CASA E COZINHA HD</channel>
<channel update="i" site="nos.pt" site_id="270" xmltv_id="fineliving.pt">Fine Living Network HD</channel>
<channel update="i" site="nos.pt" site_id="538" xmltv_id="zapviva.pt">ZAP Viva HD</channel>
<channel update="i" site="nos.pt" site_id="236" xmltv_id="fightnetwork.pt">Fight Network</channel>
<channel update="i" site="nos.pt" site_id="109" xmltv_id="france24i.pt">France 24 (I)</channel>
<channel update="i" site="nos.pt" site_id="132" xmltv_id="france24f.pt">France 24 (F)</channel>
<channel update="i" site="nos.pt" site_id="55" xmltv_id="rainews24.pt">Rai News 24</channel>
<channel update="i" site="nos.pt" site_id="108" xmltv_id="aljazeeraenglish.pt">Al Jazeera</channel>
<channel update="i" site="nos.pt" site_id="172" xmltv_id="tve24h.pt">TVE 24h</channel>
<channel update="i" site="nos.pt" site_id="124" xmltv_id="bntworld.pt">BNT World</channel>
<channel update="i" site="nos.pt" site_id="343" xmltv_id="stv.pt">STV Notícias</channel>
<channel update="i" site="nos.pt" site_id="237" xmltv_id="tcvinternational.pt">TCV Internacional</channel>
<channel update="i" site="nos.pt" site_id="53" xmltv_id="tv5mondeeurope.pt">TV5 Monde</channel>

Obrigado mais uma vez por partilhares e ajudares a comunidade.

**Comment by f0nZ** [comment]
Done
