### ISSUE TITLE
Ícones dos canais

### ISSUE THREAD

**Issue by base08** [f0nZ/epg-tv-portuguesa#2]
Viva Nuno,

Há dias fiz um clean install no meu setup Kodi e perdi os logos dos canais pois a cache dos logos foi-se... Reparei que o XML não inclui links dos logos como antigamente... Não sendo essencial se for possível ser corrigido era óptimo!

Cumprimentos!

**Comment by f0nZ** [comment]
Se por ventura o XML tinha links para os logos não era algo intencional
visto que os mesmos eram obtidos pelo guia da vodafone. Como esse guia foi
abaixo, mudei para a informação dos canais recebida pela MEO. Provavelmente
não fornece os logos.

No entanto se quiser, tem uma pasta no meu git com nome 'logos' que basta
copiar para o dispositivo que tiver serviço IPTV

Cumprimentos

base08 <notifications@github.com> escreveu no dia domingo, 11/08/2019 à(s)
19:21:
