### ISSUE TITLE
Vodafone EPG update

### ISSUE THREAD

**Issue by higuita** [f0nZ/epg-tv-portuguesa#4]
Hi

I just build a new shell script to get the vodafone EPG from a new source, you can get the needed guidelines to use it here:

https://github.com/higuita/vodafone.pt-xmltv/blob/master/shell/tv_grab_pt_vdf3.sh

Later it will be ported to perl and added again to xmltv project, but feel free to resuse it

**Comment by rickytugapt** [comment]
Hi higuita, i tried to use your script in raspian. I had to install jq and awk dependencies, and after that the script works great but the generated file has only the above header. Do you have an ideia what could be wrong?

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv source-info-url="https://www.vodafone.pt/pacotes/televisao/em-todos-ecras.html#computador" source-in$

  </channel>
</tv>
`
