### ISSUE TITLE
Utilização errada do xmltv_ns

### ISSUE THREAD

**Issue by soloam** [f0nZ/epg-tv-portuguesa#8]
Boa tarde, acho que a utilização do campo xmltv_ns está errada tanto quanto sei S01E10 deverá ser 0.9. e S01E01 sera 0.0. sendo que o padrão é s.e.p/n onde: 
s = Season - 1
e = Episódio - 1
p = parte
n = numero de partes

S01E10 = 0.9.
S02E10 = 1.9.
S03E01 = 2.0.

Já agora com que regularidade é que o ficheiro é actualizado?

Abraço

**Comment by xppx99** [comment]
Boa tarde, 
Confirmo o que o soloam refere! É possível alterar este mecanismo (xmltv_ns) para o formato correto? 

Outra opçao sera manter os valores usados atualmente, mas alterar a TAG de "xmltv_ns" para "online", como mostro no exemplo da figura seguinte:
![image](https://user-images.githubusercontent.com/52202278/87959501-e7c63880-caaa-11ea-844c-64fdc805e107.png)

**Comment by xppx99** [comment]
Viva, 
Para quem estiver interessado, existe uma maneira fácil de ultrapassar este problema. No meu caso fiz replace da string "xmltv_ns" por "onscreen". Em linux é só questão de elborar um script com a linha de código "sed -i 's/xmltv_ns/onscreen/g' ficheiro.xml" e meter um cron sincrono para ir sacar o ficheiro e correr este script de seguida.
